### ISSUE TITLE
Consistency analysis module improvements

### ISSUE THREAD

**Issue by JohnSSB** [dhis2/who-data-quality-app#16]
1. Change default on 'criteria' from 33% to 0% or remove it altogether.

2. We have not been able to identify the difference between "Totals" and "Details". If there is no difference, the option should be removed.

3. 'District' as default on 'Disaggregation' under 'Orgunit'.

4. Add the opportunity to compare a specific month (eg April 2017) with the previous releases of April (April 2016, April 2015, April 2014, ..., April N) during 'Period'.

5. Some variables should not be aggregated on month to get the year. Eg. doctors, beds, etc. Is it possible to enter a functionality where you can get an average so that the numbers do not become x12? The error may be more in the main program?

6. Remove "dropout" / redefine "dropout" unless this is a known term in DHIS2. As we see it, "dropout" should refer to whether unique devices / people drop out of or continue a program (panel data)

**Comment by olavpo** [comment]
1. for discussion
2. in the DQ demo database there is no difference because categories are not used for disaggregations, but elsewhere this options changes between showing e.g. BCG doses (total) vs BCG doses < 1 year; BCG doses 1+ years.
3. the level varies by country and user. Currently the default is the level immediately below where the user is assigned (i.e. not hardcoded to region). Can discuss whether the most appropriate is one or two levels below user, or if it needs to be configurable.
4. #42 
5. this is part of the dhis2 configuration. Infrastructure-type data should generally have "average" as aggregation operator, in which case that will be used by the DQ tool as well
6. I think this is well know?
